# Generated by Django 5.0.6 on 2024-05-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproducts',
            name='image',
            field=models.ImageField(upload_to='products/products'),
        ),
    ]
